name: continuos integration
on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"
jobs:
  gradle-build:
    name: Gradle build
    runs-on: [self-hosted]
    steps:
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check out commit
      uses: actions/checkout@v2
    - name: Download Jfrog CLI
      uses: jfrog/setup-jfrog-cli@v2
      with:
        version: 2.9.0
    - name: Configure Jfrog CLI
      run:  |
        jfrog config add artifactory --url=http://159.89.158.231:8082 --user=${{ secrets.JFROG_USER }} --password={{ secrets.JFROG_PASSWORD }} --interactive=false
    - name: Configure Jfrog CLI Gradle
      run:  |
        jfrog gradle-config --server-id-resolve artifactory --server-id-deploy artifactory --repo-resolve gradle-virtual --repo-deploy gradle-virtual
    - name: Gradle clean compile
      run: jfrog rt gradle clean artifactoryPublish -b build.gradle --build-name $GITHUB_REPOSITORY --build-number $GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
